export { default as login } from './login.png'
export { default as signup } from './signup.png'
export { default as logo } from './logo.svg'
export { default as logoHeader } from './logo-header.svg'
export { default as chicken } from './chicken.png'
export { default as sorvete } from './sorvete.png'
